### ISSUE TITLE
Add mysql data storage

### ISSUE THREAD

**Issue by ghost** [LXGaming/BungeePlayer#1]
I think this will be really helpful. Creating a table with the users record like:

uuid | ip | x | y | z | pitch | server
----- | -- | - | - | - | ------ | -------
asdasd-asdasd | 127.0.0.1 | 7 | 7 | 64 | 33 | Lobby

**Comment by James137137** [comment]
Wouldn't that cost a lot of resources doing that? Mysql is a lot slower than Ram. 

I suppose it could log every X min... (and at logout)

**Comment by ghost** [comment]
@James137137 its not, there some light resources for work with jdbc on java
